# Add Homebrew repositories
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'homebrew/core'
tap 'homebrew/gui'
tap 'homebrew/services'
tap 'homebrew/versions'

# Install packages
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash-completion'
brew 'coreutils'
brew 'direnv'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'htop'
brew 'httpie'
brew 'imagemagick'
brew 'jq'
brew 'libusb-compat'
brew 'libssh2'
brew 'libxslt'
brew 'libyaml'
brew 'midnight-commander'
brew 'mongodb', restart_service: true
brew 'ncdu'
brew 'node@8', link: true
brew 'openssl'
brew 'rbenv'
brew 'rbenv-bundler-ruby-version'
brew 'readline'
brew 'ruby-build'
brew 's3cmd'
brew 'shellcheck'
brew 'terminal-notifier'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'yarn'

# Install desktop apps
cask 'insomnia'
cask 'keepassx'
cask 'macdown'
cask 'meld'
